-- Contacts upsert support
create unique index if not exists uq_contacts_whatsapp_digits
on public.contacts (whatsapp_digits)
where whatsapp_digits is not null and whatsapp_digits <> '';

-- Campaign audience selection
create table if not exists public.campaign_contacts (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.campaigns(id) on delete cascade,
  contact_id uuid not null references public.contacts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (campaign_id, contact_id)
);

create index if not exists idx_campaign_contacts_campaign
  on public.campaign_contacts (campaign_id);

create index if not exists idx_campaign_contacts_contact
  on public.campaign_contacts (contact_id);
